version: '3.5'

networks:
  default:
    name: compose_gitlab

services:
  # Redis
  redis:
    image: redis:4.0-alpine
    restart: always
    container_name: gitlab-redis
    ports:
      - 127.0.0.1:6379:6379

  # Postgresql
  postgresql:
    image: postgres:10.4-alpine
    restart: always
    container_name: gitlab-postgres
    environment:
      PGDATA: /postgresql/data
      POSTGRES_USER: gitlab
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ${DATA_PATH}/gitlab-postgres:/postgresql

  # GitLab
  gitlab:
    image: gitlab/gitlab-ee
    restart: always
    container_name: gitlab
    hostname: gitlab.nmtuan.space
    links: # Make sure components are up & healthy before spinning up gitlab
      - postgresql:postgresql
      - redis:redis
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false # Disable built-in postgresql, use configured external
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = ""
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlab" # Need to create database before-hand
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false # Disable built-in redis, use configured external
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url 'https://gitlab.nmtuan.space'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - 80:80
      - 443:443 # Enable if you support ssl/tls
      # - 22:22 # Enable if you to want ssh to container (better to docker exec)
    volumes:
      - ${DATA_PATH}/gitlab/config:/etc/gitlab
      - ${DATA_PATH}/gitlab/logs:/var/log/gitlab
      - ${DATA_PATH}/gitlab/data:/var/opt/gitlab

