version: '3.5'

networks:
  default:
    name: gitea

services:
  server:
    image: gitea/gitea:latest
    restart: always
    container_name: gitea
    environment:
      - APP_NAME=GitRocket
      - RUN_MODE=prod
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /mnt/disks/git-data:/data
    ports:
      - 80:8080
      - 443:8443
      - 0.0.0.0:22:22

