version: '3'

services:
  mongodb-2.4:
    image: mongo:2.4
    restart: always
    container_name: mongodb-2.4
    command: mongod --config /mongodb/mongod.conf
    ports:
      - "127.0.0.1:28000:27017"
      - "127.0.0.1:28001:28017"
    volumes:
      - ~/Data/mongodb-2.4:/mongodb
  mongodb-3.4:
    image: mongo:3.4
    restart: always
    container_name: mongodb-3.4
    command: mongod --config /mongodb/mongod.conf
    ports:
      - "127.0.0.1:27017:27017"
      - "127.0.0.1:28017:28017"
    volumes:
      - ~/Data/mongodb-3.4:/mongodb
  postgres-9.6:
    image: postgres:9.6
    restart: always
    container_name: postgres-9.6
    environment:
      PGDATA: /postgresql/data
      POSTGRES_USER: postgres
    command: postgres -c config_file=/postgresql/postgresql.conf
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ~/Data/postgres-9.6:/postgresql
  elasticsearch-5.1:
    image: elasticsearch:5.1-alpine
    restart: always
    container_name: elasticsearch-5.1
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - ~/Data/elasticsearch-5.1:/usr/share/elasticsearch/data
