version: '3'

services:
  mongodb-2.4:
    image: mongo:2.4
    restart: always
    command: mongod --config /mongodb/mongod.conf
    ports:
      - "127.0.0.1:28000:27017"
      - "127.0.0.1:28001:28017"
    volumes:
      - ~/Data/mongodb-2.4:/mongodb
  mongodb-3.4:
    image: mongo:3.4
    restart: always
    command: mongod --config /mongodb/mongod.conf
    ports:
      - "127.0.0.1:27017:27017"
      - "127.0.0.1:28017:28017"
    volumes:
      - ~/Data/mongodb-3.4:/mongodb
  postgres-9.6:
    image: postgres:9.6
    restart: always
    environment:
      PGDATA: /postgresql/data
    command: postgres -c config_file=/postgresql/postgresql.conf
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ~/Data/postgres-9.6:/postgresql