REVOKE ALL ON DATABASE {{ database }} FROM PUBLIC;
REVOKE ALL ON SCHEMA {{ schema }} FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA {{ schema }} FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA {{ schema }} FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA {{ schema }} FROM PUBLIC;
 
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM PUBLIC;

-- service role
CREATE ROLE service;
 
-- administrator role
CREATE ROLE administrator;
GRANT ALL PRIVILEGES ON DATABASE {{ database }} TO administrator;
GRANT ALL PRIVILEGES ON SCHEMA {{ schema }} TO administrator;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{ schema }} TO administrator;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA {{ schema }} TO administrator;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA {{ schema }} TO administrator;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO administrator;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO administrator;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO administrator;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO administrator;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO administrator;
 
-- operator role
CREATE ROLE operator;
GRANT CONNECT ON DATABASE {{ database }} TO operator;
GRANT USAGE ON SCHEMA {{ schema }} TO operator;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{ schema }} TO operator;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA {{ schema }} TO operator;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO operator;
ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO operator;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO operator;
 
-- developer role
CREATE ROLE developer;
GRANT CONNECT ON DATABASE {{ database }} TO developer;
GRANT USAGE ON SCHEMA {{ schema }} TO developer;
GRANT SELECT ON ALL TABLES in SCHEMA {{ schema }} TO developer;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA {{ schema }} TO developer;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO developer;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO developer;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO developer;
