CREATE ROLE {{ user }} WITH
    LOGIN
    INHERIT
    PASSWORD '{{ password }}'
    CONNECTION LIMIT -1
    IN ROLE service;
 
-- Example service with full privileges
-- GRANT ALL PRIVILEGES ON DATABASE {{ database }} TO {{ user }};
-- GRANT ALL PRIVILEGES ON SCHEMA {{ schema }} TO {{ user }};
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{ schema }} TO {{ user }};
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA {{ schema }} TO {{ user }};
-- GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA {{ schema }} TO {{ user }};
-- ALTER DEFAULT PRIVILEGES GRANT ALL ON SCHEMAS TO {{ user }};
-- ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO {{ user }};
-- ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO {{ user }};
-- ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO {{ user }};
-- ALTER DEFAULT PRIVILEGES GRANT ALL ON TYPES TO {{ user }};

-- Example service with restricted privileges
GRANT CONNECT ON DATABASE {{ database }} TO {{ user }};
GRANT USAGE ON SCHEMA {{ schema }} TO {{ user }};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{ schema }} TO {{ user }};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA {{ schema }} TO {{ user }};
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA {{ schema }} TO {{ user }};
ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {{ user }};
ALTER DEFAULT PRIVILEGES GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO {{ user }};
ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO {{ user }};
